version: '3'

services:
  php-fpm:
    build:
      context: .
      dockerfile: DockerFile

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/DockerFile
    volumes:
      - ../src:/var/www/html/
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "4000:80"
      - "443:443"

